apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3proxy.fullname" . }}
  labels:
    {{- include "s3proxy.labels" . | nindent 4 }}
type: Opaque
data:
{{- if and .Values.config.identity .Values.config.credential }}
  # S3Proxy authentication credentials (for clients connecting to s3proxy)
  # Using uppercase names to match environment variable conventions
  S3PROXY_IDENTITY: {{ .Values.config.identity | b64enc | quote }}
  S3PROXY_CREDENTIAL: {{ .Values.config.credential | b64enc | quote }}
{{- end }}
  
{{- if or (eq .Values.config.backend.provider "aws-s3") (eq .Values.config.backend.provider "s3") }}
  # AWS S3 backend credentials
  {{- if .Values.config.backend.awsS3.accessKeyId }}
  JCLOUDS_IDENTITY: {{ .Values.config.backend.awsS3.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.backend.awsS3.secretAccessKey }}
  JCLOUDS_CREDENTIAL: {{ .Values.config.backend.awsS3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- else if or (eq .Values.config.backend.provider "azureblob") (eq .Values.config.backend.provider "azureblob-sdk") }}
  # Azure Blob backend credentials
  {{- if .Values.config.backend.azureblob.account }}
  JCLOUDS_IDENTITY: {{ .Values.config.backend.azureblob.account | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.backend.azureblob.key }}
  JCLOUDS_CREDENTIAL: {{ .Values.config.backend.azureblob.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.backend.azureblob.sasToken }}
  JCLOUDS_AZURE_SAS: {{ .Values.config.backend.azureblob.sasToken | b64enc | quote }}
  {{- end }}
  {{- else if eq .Values.config.backend.provider "google-cloud-storage" }}
  # Google Cloud Storage backend credentials
    {{- if .Values.config.backend.googleCloudStorage.clientEmail }}
  JCLOUDS_IDENTITY: {{ .Values.config.backend.googleCloudStorage.clientEmail | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.backend.googleCloudStorage.privateKey }}
  JCLOUDS_CREDENTIAL: {{ .Values.config.backend.googleCloudStorage.privateKey | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.config.backend.provider "b2" }}
  # Backblaze B2 backend credentials
    {{- if .Values.config.backend.b2.account }}
  JCLOUDS_IDENTITY: {{ .Values.config.backend.b2.account | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.backend.b2.applicationKey }}
  JCLOUDS_CREDENTIAL: {{ .Values.config.backend.b2.applicationKey | b64enc | quote }}
    {{- end }}
  {{- else if eq .Values.config.backend.provider "openstack-swift" }}
  # OpenStack Swift backend credentials
    {{- if .Values.config.backend.swift.tenantName }}
      {{- if .Values.config.backend.swift.userName }}
  JCLOUDS_IDENTITY: {{ printf "%s:%s" .Values.config.backend.swift.tenantName .Values.config.backend.swift.userName | b64enc | quote }}
      {{- end }}
    {{- end }}
  {{- if .Values.config.backend.swift.password }}
  JCLOUDS_CREDENTIAL: {{ .Values.config.backend.swift.password | b64enc | quote }}
  {{- end }}
{{- end }}

