apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3proxy.fullname" . }}
  labels:
    {{- include "s3proxy.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "s3proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        {{- include "s3proxy.selectorLabels" . | nindent 8 }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "s3proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: merge-configs
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.configMergeImage.repository }}:{{ .Values.configMergeImage.tag }}"
          imagePullPolicy: {{ .Values.configMergeImage.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              set -e
              echo "Merging configuration files..."

              # Check if secret properties file exists
              SECRET_FILE="/secret/secret.properties"

              # Loop through all properties files in the config directory
              for config_file in /config/*.properties
              do
                if [ -f "$config_file" ]
                then
                  # Get the filename
                  filename=$(basename "$config_file")
                  output_file="/merged-config/$filename"

                  echo "Processing $filename..."

                  # Copy base config file to output
                  cp "$config_file" "$output_file"

                  # If secret file exists, append its contents (overriding duplicates)
                  if [ -f "$SECRET_FILE" ]
                  then
                    echo "" >> "$output_file"  # Add newline separator
                    cat "$SECRET_FILE" >> "$output_file"
                  fi
                fi
              done

              echo "Configuration files merged successfully."
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: secret-config
              mountPath: /secret
              readOnly: true
            - name: merged-config
              mountPath: /merged-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - java
          args:
            - -DLOG_LEVEL={{ .Values.config.logLevel | upper }}
            - -jar
            - /opt/s3proxy/s3proxy
{{- if .Values.config.backends.filesystem.enabled }}
            - "--properties"
            - "/merged-config/backend-filesystem.properties"
{{- end }}
{{- if .Values.config.backends.transient.enabled }}
            - "--properties"
            - "/merged-config/backend-transient.properties"
{{- end }}
{{- if .Values.config.backends.s3.enabled }}
            - "--properties"
            - "/merged-config/backend-s3.properties"
{{- end }}
{{- if .Values.config.backends.azureblob.enabled }}
            - "--properties"
            - "/merged-config/backend-azureblob.properties"
{{- end }}
{{- if .Values.config.backends.googleCloudStorage.enabled }}
            - "--properties"
            - "/merged-config/backend-google-cloud-storage.properties"
{{- end }}
{{- if .Values.config.backends.b2.enabled }}
            - "--properties"
            - "/merged-config/backend-b2.properties"
{{- end }}
{{- if .Values.config.backends.openstackSwift.enabled }}
            - "--properties"
            - "/merged-config/backend-openstack-swift.properties"
{{- end }}
{{- if .Values.config.backends.rackspaceCloudfiles.enabled }}
            - "--properties"
            - "/merged-config/backend-rackspace-cloudfiles.properties"
{{- end }}
{{- with .Values.extraEnvVars }}
          env:
            {{- toYaml . | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: merged-config
              mountPath: /merged-config
              readOnly: true
{{- if .Values.config.backends.filesystem.enabled }}
  {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.config.backends.filesystem.basedir }}
  {{- end }}
{{- end }}
{{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "s3proxy.fullname" . }}
        - name: secret-config
          secret:
            secretName: {{ include "s3proxy.fullname" . }}
        - name: merged-config
          emptyDir: {}
{{- if .Values.config.backends.filesystem.enabled }}
  {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "s3proxy.fullname" .) }}
  {{- end }}
{{- end }}
{{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
