{{- if and (or (eq .Values.config.backend.provider "filesystem") (eq .Values.config.backend.provider "filesystem-nio2")) .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "s3proxy.fullname" . }}
  labels:
    {{- include "s3proxy.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
  {{- end }}
{{- end -}}

