{{ $portName := ternary "https" "http" .Values.config.tls.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "comet-common.names.fullname" . }}
  labels:
    {{- include "comet-common.labels.base" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ $portName }}
  selector:
    {{- include "s3proxy.selectorLabels" . | nindent 4 }}
