name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - charts/s3proxy/**

jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Render helm docs inside the README.md and push changes back to PR branch
        uses: losisin/helm-docs-github-action@v1
        with:
          output-file: ../../README.md
          template-files: README.md.gotmpl
          git-push: true
          git-push-user-name: "CometActions"
          git-push-user-email: "github-actions@comet.com"
          git-commit-message: "Update Helm documentation"
  release:
    runs-on: ubuntu-latest
    needs:
      - update-readme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config --global user.name 'Github Actions (${{ github.actor }})'
          git config --global user.email 'github-actions@comet.com'

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.3
        with:
          oci_registry: ghcr.io/comet-ml
          tag_name_pattern: ''
          oci_username: github-actions
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
