name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - values.yaml
      - Chart.yaml
      - templates/**

jobs:
  release:
    runs-on: org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-dpth: 0
          fetch-tags: true

      - name: Configure Git
        run: |
          git config --global user.name 'Github Actions (${{ github.actor }})'
          git config --global user.email 'github-actions@comet.com'

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.3
        with:
          charts_dir: .
          oci_registry: ghcr.io/comet-ml
          oci_username: github-actions
          oci_password: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
